import apiClient from '../services/apiClient'
import { deliverOtpEmail } from './otpEmailService'

export type UserRole = 'inventory_manager' | 'warehouse_staff'
export type UserStatus = 'active' | 'disabled'

export interface UserRecord {
  id: string
  fullName: string
  email: string
  role: UserRole
  organization: string
  status: UserStatus
  createdAt: string
  phoneNumber?: string
}

interface AuthResult<T> {
  ok: boolean
  data?: T
  error?: string
}

interface SignupInput {
  fullName: string
  email: string
  password: string
  role?: UserRole
  organization?: string
}

interface LoginInput {
  email: string
  password: string
  rememberMe: boolean
}

interface PasswordChangeInput {
  currentPassword: string
  nextPassword: string
}

const TOKEN_KEY = 'auth_token'
const USER_KEY = 'auth_user'

// ── Helpers ──

function storeAuth(token: string, user: UserRecord): void {
  localStorage.setItem(TOKEN_KEY, token)
  localStorage.setItem(USER_KEY, JSON.stringify(user))
}

function clearAuth(): void {
  localStorage.removeItem(TOKEN_KEY)
  localStorage.removeItem(USER_KEY)
}

// ── Public API ──

export function getCurrentUser(): UserRecord | null {
  const raw = localStorage.getItem(USER_KEY)
  if (!raw) return null
  try {
    return JSON.parse(raw) as UserRecord
  } catch {
    return null
  }
}

export function getToken(): string | null {
  return localStorage.getItem(TOKEN_KEY)
}

export function logout(): void {
  clearAuth()
}

export async function signup(input: SignupInput): Promise<AuthResult<null>> {
  try {
    await apiClient.post('/auth/signup', {
      fullName: input.fullName,
      email: input.email,
      password: input.password,
      role: input.role,
      organization: input.organization,
    })
    return { ok: true, data: null }
  } catch (err: any) {
    const msg = err.response?.data?.error || 'Signup failed'
    return { ok: false, error: msg }
  }
}

export async function login(input: LoginInput): Promise<AuthResult<UserRecord>> {
  try {
    const res = await apiClient.post('/auth/login', {
      email: input.email,
      password: input.password,
    })
    const { token, user } = res.data
    storeAuth(token, user)
    return { ok: true, data: user }
  } catch (err: any) {
    const msg = err.response?.data?.error || 'Login failed'
    return { ok: false, error: msg }
  }
}

export async function requestPasswordReset(
  email: string,
): Promise<AuthResult<{ otp: string; sentVia: 'email' | 'demo' }>> {
  try {
    const res = await apiClient.post('/auth/request-otp', { email })
    const otp = res.data.otp

    if (!otp) {
      return { ok: false, error: 'OTP was not generated by server' }
    }

    const emailDelivery = await deliverOtpEmail(email, otp)
    if (!emailDelivery.ok) {
      return { ok: false, error: emailDelivery.error || 'Failed to send OTP email' }
    }

    return {
      ok: true,
      data: {
        otp: emailDelivery.sentVia === 'email' ? '' : otp,
        sentVia: emailDelivery.sentVia || 'demo',
      },
    }
  } catch (err: any) {
    const msg = err.response?.data?.error || 'Failed to request OTP'
    return { ok: false, error: msg }
  }
}

export async function verifyPasswordResetOtp(
  email: string,
  otp: string,
): Promise<AuthResult<null>> {
  try {
    await apiClient.post('/auth/verify-otp', { email, otp })
    return { ok: true, data: null }
  } catch (err: any) {
    const msg = err.response?.data?.error || 'OTP verification failed'
    return { ok: false, error: msg }
  }
}

export async function resetPasswordWithOtp(
  email: string,
  password: string,
): Promise<AuthResult<null>> {
  try {
    await apiClient.post('/auth/reset-password', { email, password })
    return { ok: true, data: null }
  } catch (err: any) {
    const msg = err.response?.data?.error || 'Password reset failed'
    return { ok: false, error: msg }
  }
}

export async function changePassword(input: PasswordChangeInput): Promise<AuthResult<null>> {
  try {
    await apiClient.put('/auth/change-password', {
      currentPassword: input.currentPassword,
      nextPassword: input.nextPassword,
    })
    return { ok: true, data: null }
  } catch (err: any) {
    const msg = err.response?.data?.error || 'Password change failed'
    return { ok: false, error: msg }
  }
}
